### PR TITLE
Rewrite check-namespace

### PR DESCRIPTION
**Pull request by allejok96**
A different approach

Line numbers on errors, looks for missing header guards, wants #include before code, detects if you open a brace outside an ifdef and close it inside the ifdef, recognizes small namespaces and ifdefs and doesn't require comment for those.

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
This looks much better. I just wrote my script as quick as possible, but this here is well structured, so I think we should take this.

Do you think you can get the [github actions](https://github.com/allejok96/lmms/actions) working? You'd need to adjust the `verify` script.

**Comment by allejok96** [comment]
Sorry won't have time for this but it's pretty easy to fix right?

**Comment by JohannesLorenz** [comment]
> Sorry won't have time for this but it's pretty easy to fix right?

I'll try now.

**Comment by JohannesLorenz** [comment]
I'll merge it over and fix the verify script in the other PR.

**Comment by JohannesLorenz** [comment]
Thanks a lot for the contribution.

**Pull request merged**
