### PR TITLE
PluginBrowser: Tree layout and search bar.

### PR DESCRIPTION
**Pull request by ghost**
:-)

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
Works like expected; you can see an Lv2 instrument in the Lv2 tab now. Many thanks :+1:

**Comment by ghost** [comment]
Ok awesome what instrument do you see? I don't see any LV2 instrument.

**Comment by JohannesLorenz** [comment]
If you install the x42 plugins, a "test signal generator" should show up. That's one of the few that are currently supported. It's only tested on Linux currently, it may not work on another OS.

**Comment by ghost** [comment]
Ah yes there is, very good! :beers: (don't like proprietary stuff anyways :-P)

**Pull request merged**
